### PR TITLE
Changed image component markup

### PR DESCRIPTION
**Pull request by peiche**
Previous markup had figcaption element as a child inside a div, which is
invalid. (See
http://www.w3.org/html/wg/drafts/html/master/single-page.html#the-figcaption-element
for reference.)

### CODE REVIEW

**Comment by bearded-avenger** [comment]
hey paul, it's perfectly semantic to have a div within a figure as far as I know

**Comment by michaelbeil** [comment]
@peiche can you create a clean branch from aesop-core master and then PR against `release/1.6.2`? 

There are a bunch of old commits here. Thanks a million"!

**Comment by bearded-avenger** [comment]
"One figcaption element, followed by flow content or flow content followed by an optional figcaption element"

flow content can include divs

**Comment by peiche** [comment]
Not according to the spec: 

4.4.12 The figcaption element
Contexts in which this element can be used:
As the first or last child of a figure element.

**Comment by peiche** [comment]
I'm not talking about the figure element. It's the figcaption that's unsemantic. Yes, you can have a div inside a figure element. But you can't have a figcaption element as a child inside a div.

**Comment by peiche** [comment]
@michaelbeil sorry, I tried to sync it against the latest first. I'll delete and start over. /facepalm

**Pull request closed without merging**
