### PR TITLE
Update i18n + Ready for Grunt-Transifex + pot + all languages 

### PR DESCRIPTION
**Pull request by fxbenard**
Don't forget to "npm update" for grunt to work with the new features ;)

More infos on how it works https://github.com/WP-Translations/grunt-transifex-wordpress

### CODE REVIEW

**Comment by bearded-avenger** [comment]
@fxbenard this is amazing! Thank you so much for this!

**Comment by fxbenard** [comment]
You're welcome, now we need to make it translated into 100 languages - we're still far away ;)

**Comment by michaelbeil** [comment]
@fxbernard i am glad we connected on transifex with the wptranslations team! this rocks. you rock.

**Comment by fxbenard** [comment]
that's the main idea behind WPT, put together devs and translators. Wait and see the api key is coming ;)

**Comment by michaelbeil** [comment]
ooh lala. looking forward to it.

**Comment by bearded-avenger** [comment]
@fxbenard what you guys are doing are what makes WordPress' future a sustainable one. :+1:

**Comment by michaelbeil** [comment]
truly @bearded-avenger ... couldn't agree more.

**Comment by fxbenard** [comment]
Best compliment I had since a long time. Thanks guys. I'm just following a crazy dream - WP for everybody in his own language. Matt talked about it lately, he borrowed my idea, hahaha.

I have a few more ideas how to improve things, if you have 5min I will be happy to discuss them with you ;) Sharing is caring!

**Comment by michaelbeil** [comment]
i would be glad to. where could we meet up? http://appear.in?

**Comment by fxbenard** [comment]
Good idea! whenever you want. Beginning of next week? Time to leave the net for me. 8PM here family time and rugby ;)

**Comment by michaelbeil** [comment]
oh yea cool cool. cheers on the night. and dude, rugby is my thing too!

**Comment by fxbenard** [comment]
Lovely - Allez les bleus
http://www.rbs6nations.com/en/home_live.php

**Comment by michaelbeil** [comment]
oh man six nations are at it. sweet.

**Pull request merged**
