### PR TITLE
Release/1.5 WP-T

### PR DESCRIPTION
**Pull request by fxbenard**
* Bump grunt wp-i18n v1.5.0 - New features remove plugin author uris from pot
* gruntfile wp standard + update
* test grunt makandpush - works - new pot for 1.5
* test grunt push TX - works - new pot on TX
* test new grunt TX - force to dl all po<10% - works

### CODE REVIEW

**Comment by michaelbeil** [comment]
This PR looks good after reviewing it, waiting on Nick.
- [x] @michaelbeil 
- [ ] @bearded-avenger

**Comment by fxbenard** [comment]
Yep sorry a little messy, not easy reviewing

**Comment by michaelbeil** [comment]
Yea, it was slightly confusing, but I eventually figured it out ;).

:+1:

**Comment by bearded-avenger** [comment]
Thanks a lot @fxbenard !!

**Comment by michaelbeil** [comment]
All clear.

**Pull request merged**
