### PR TITLE
remove iframe border for kickstarter videos

### PR DESCRIPTION
**Pull request by dryanmedia**

### CODE REVIEW

**Comment by michaelbeil** [comment]
Oh nice! Do you have a specific Kickstarter video id we could check this with? I tested locally with another Kickstarter vid and all seems to work well.

**Comment by michaelbeil** [comment]
Old look:
screen shot on 2015-04-21 at 13_16_49


New look: 
screen shot 2015-04-21 at 1 17 21 pm

**Comment by dryanmedia** [comment]
@michaelbeil this is the video I was testing on: https://www.kickstarter.com/projects/myqblinks/qmote-the-water-resistant-internet-remote-for-smar/widget/video.html. 

Noticed this while looking at another issue that's been bugging me... about to open ticket.

**Comment by michaelbeil** [comment]
Got it. Also, can you PR this against release/1.6.2? Thanks a million!

**Comment by dryanmedia** [comment]
Sure thing!

**Comment by michaelbeil** [comment]
Thanks!

**Pull request closed without merging**
